### ISSUE TITLE
Penambahan Rombel Saat Input Lingkup Materi dan TP

### ISSUE THREAD

**Issue by ngurahdinata** [nandangsetianugraha/APINS-14#27]
Hallo min ijin sharing, saya memiliki kendala saat mau me input data LM dan TP, daftar rombel tidak keluar pada menu lingkup materi, rombel sudah di settinh tetapi tidak muncul saat pengisian LM TP saya menggunakan user admin, adalah solusinya ??
![IMG_7256](https://github.com/nandangsetianugraha/APINS-14/assets/62980291/ab1beb4b-3366-4915-8c47-fd142daa2671)

**Comment by nandangsetianugraha** [comment]
Untuk penamaan rombel gunakan kombinasi Angka dan Huruf, contohnya 1A, 1B, 2A, 3B, dst ...

**Comment by nandangsetianugraha** [comment]
Untuk penamaan rombel gunakan kombinasi Angka dan Huruf, contohnya 1A, 1B, 2A, 3B, dst

**Comment by ngurahdinata** [comment]
hallo terimaksih banyak atas penjelasannya, ijin bertanya lagi. untuk akses
siswanya disaat saya login menggunakan username dan password tidak bisa ke
halaman utama hanya terdiam di halaman login, di config.php alamat web
sudah saya rubah dengan menambahkan urlwebiste/siswa/ tetatpi disaat login
dan berhasil login tidak bisa ke menu utama siswa, jika url ini "
urlwebiste/siswa/" dirubah dengan menghapus "/siswa/ bisa ke halaman utama
siswa, tetapi jika login ulang tidak, mohon pencerahannya min dan
terimakasih banyak juga sudah sharing ilmu bagi saya yg baru masuk ke dunia
perkodingan

Pada Jum, 12 Apr 2024 pukul 17.07 Nandang Setia Nugraha <
***@***.***> menulis:

**Comment by nandangsetianugraha** [comment]
Untuk login siswa memang masih error pada file login.js
Belum diperbaiki.
Tapi untuk demo login siswa bisa dilihat di web demo https://demos.sdi-aljannah.web.id/siswa

**Comment by ngurahdinata** [comment]
oalahh okee bang, saya kira bisa diakalin

Pada Sab, 13 Apr 2024 pukul 19.29 Nandang Setia Nugraha <
***@***.***> menulis:
