### ISSUE TITLE
LOADING Saat login

### ISSUE THREAD

**Issue by khairul-amin** [nandangsetianugraha/APINS-14#31]
Halo bang, saya udah coba install di hosting tetapi ketika login hanya muter2 loading nya

![image](https://github.com/user-attachments/assets/dc3d29e8-e029-499f-99ea-bffef00180b5)

bagian konfigurasi alamat web di config/config.php
dan database di config/db_connect.php

juga sudah sesuai

**Comment by khairul-amin** [comment]
Ketika dijalankan di local bisa berjalan dengan normal

**Comment by nandangsetianugraha** [comment]
Kalau alamat web atau subdomainnya menggunakan folder  ubah
$halaman = $params[1];
$tipe = count($params)>2 ? $params[2] : '';
$act = count($params)>3 ? $params[3] : '';

Menjadi
$halaman = $params[2];
$tipe = count($params)>3 ? $params[3] : '';
$act = count($params)>4 ? $params[4] : '';

Contohnya http://nilai.domainku.com/apins/

Alamat url pada config.php harus diakhiri dengan tanda slash (/)

**Comment by khairul-amin** [comment]
script nya Langsung di didalam folder subdomain nya bang,
https://rapot.rabbanibengkulu.sch.id

jadi langsung di dalam folder
rapot.rabbanibengkulu.sch.id

dan ketika di masukkan password atau username salah juga tetap muter2 bang.

**Comment by shoelyshtya** [comment]
php terlalu tinggi

**Comment by khairul-amin** [comment]
PHP 7.2 bang

Pada Jum, 9 Agu 2024 00.12, shoelysh ***@***.***> menulis:

**Comment by nandangsetianugraha** [comment]
Close
