### ISSUE TITLE
terjadi kesalahan

### ISSUE THREAD

**Issue by wirakarta** [nandangsetianugraha/APINS-14#7]
![image](https://github.com/nandangsetianugraha/APINS-14/assets/154517573/e60003f9-ab2a-42c3-887c-431ec67a0932)

mohon maaf pak, data tidak nongol kenapa ya? mohon pencerahan

**Comment by shoelyshtya** [comment]
> ![image](https://private-user-images.githubusercontent.com/154517573/300233266-e60003f9-ab2a-42c3-887c-431ec67a0932.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0NjU4OTUsIm5iZiI6MTcwNjQ2NTU5NSwicGF0aCI6Ii8xNTQ1MTc1NzMvMzAwMjMzMjY2LWU2MDAwM2Y5LWFiMmEtNDJjMy04ODdjLTQzMWVjNjdhMDkzMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOFQxODEzMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZThiMGUyM2Q4ZTRmNTQwM2YyMDJiZmM3MzRhMGU1MTQ0MGEwZWE3MmYxNzExZTZlNGFiNjc4N2MzMTBiMmZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mB3VVFeTDKVfQbbrNc4hmBs5whI6Fkl5s26e46pPpys)
> 
> mohon maaf pak, data tidak nongol kenapa ya? mohon pencerahan

silahkan rubah ke $halaman = $params[2];
$tipe = count($params)>3 ? $params[3] : '';
$act = count($params)>4 ? $params[4] : '';
file index.php
line 6,7,8

**Comment by wahfaweb** [comment]
Assalamualaikum ...
Kang Kalau seperti ini terus kenapa ya ?

DataTables warning: table id=datatable-1 - Ajax error. For more information about this error, please see http://datatables.net/tn/7
